# type: ignore

Import('env')

env = env.Clone()

env = SConscript("../godot-cpp/SConstruct")

env.Append(CPPPATH=[
    "SKLibretro/external/",
    "SKLibretro/external/godot-cpp/",
    "SKLibretro/external/godot-cpp/include/",
    "SKLibretro/external/godot-cpp/gen/include/",
    "SKLibretro/external/libretro-common/include/",
])

is_windows = env["platform"] == "windows"
is_android = env["platform"] == "android"

if is_windows:
    env.Append(CPPPATH=["SKLibretro/external/SDL3/include/"])
    env.Append(CXXFLAGS=["/std:c++latest"])
    env.Append(LIBPATH=[r"SKLibretro/external/SDL3/lib/x64"])
    env.Append(LIBS=["user32", "gdi32", "opengl32", "SDL3"])
    env.Append(LINKFLAGS=['/IGNORE:4099'])

if is_android:
    env.Append(CXXFLAGS=["-std=c++20"])
    env.Append(LIBS=["dl", "log", "EGL", "GLESv3"])

sources = Glob("SKLibretro/src/*.cpp")
sources.extend(Glob("SKLibretro/external/libretro-common/compat/*.c"))
sources.remove(File("SKLibretro/external/libretro-common/compat/compat_ifaddrs.c"))
sources.extend(Glob("SKLibretro/external/libretro-common/encodings/*.c"))

sources.append("SKLibretro/external/libretro-common/audio/conversion/s16_to_float.c")
sources.append("SKLibretro/external/libretro-common/features/features_cpu.c")
sources.append("SKLibretro/external/libretro-common/gfx/scaler/pixconv.c")
sources.append("SKLibretro/external/libretro-common/string/stdstring.c")
sources.append("SKLibretro/external/libretro-common/file/file_path.c")
sources.append("SKLibretro/external/libretro-common/time/rtime.c")
sources.append("SKLibretro/external/libretro-common/streams/file_stream.c")
sources.append("SKLibretro/external/libretro-common/vfs/vfs_implementation.c")

lib_prefix = "lib" if is_android else ""
library = env.SharedLibrary("../RetroVR/SKLibretro/{}sklibretro.{}.{}.{}{}".format(lib_prefix, env["platform"], env["target"], env["arch"], env["SHLIBSUFFIX"]), source=sources)

Default(library)