# type: ignore

VariantDir('Temp', '.', duplicate=0)
env = Environment()

import os
output_dir = os.environ.get('GODOT_PDFIUM_OUTPUT_DIR', '#../RetroXR/godot-pdfium')

SConscript('Temp/SConscript', exports=['env', 'output_dir'])
