## ControllerPlug — the grabbable plug at the end of a retro controller's cable.
## Must be in the "controller_plug" group so RetroSystem controller ports accept it.
class_name ControllerPlug
extends XRToolsPickable


## The controller (RetroController or RayGun) that owns this plug.
var _controller: Node3D = null

## Device type exposed so system.gd can read it without knowing the controller type.
var device_type: int = 1  # RETRO_DEVICE_JOYPAD
## Systemid of the controller on the other end; "" = fits any port.
var systemid: String = ""

## Local point the cable leaves this plug at, fed to VerletRope.end_anchor_offset.
## Zero for the generic cylinder plug, whose origin already sits mid-barrel with
## the strain relief covering it; a bespoke connector sets its own cable boss in
## set_plug_mesh, since its origin is the SEATING reference buried in the shell.
var cable_anchor: Vector3 = Vector3.ZERO


func _ready() -> void:
	super._ready()
	add_to_group("controller_plug")


## Returns the owning controller (RetroController or RayGun).
func get_controller() -> Node3D:
	return _controller


## Swap the generic cylinder plug for a device-accurate connector mesh — the PS/2
## plugs on the keyboard and mouse, generated by Tools/gen_ps2_plug.gd. A blank or
## missing path leaves the generic plug in place. The mesh is authored in this
## node's own frame (connector on +Z, cable trailing -Z), so it needs no transform
## here.
func set_plug_mesh(path: String) -> void:
	if path.is_empty() or has_node("PlugModel") or not ResourceLoader.exists(path):
		return
	var mesh := load(path) as Mesh
	if mesh == null:
		return
	var mi := MeshInstance3D.new()
	mi.name = "PlugModel"
	mi.mesh = mesh
	add_child(mi)
	for generic in ["PlugTip", "StrainRelief"]:
		var g := get_node_or_null(generic) as MeshInstance3D
		if g != null:
			g.hide()
	# Where the cable leaves this connector: the centre of the shell's back face
	# (min Z — the cable trails -Z, matching VerletRope.plug_exit_axis).
	var ab: AABB = mesh.get_aabb()
	cable_anchor = Vector3(ab.get_center().x, ab.get_center().y, ab.position.z)


## Called by the owning controller when the cable is spawned.
func set_controller(controller: Node3D) -> void:
	_controller = controller
	if "device_type" in controller:
		device_type = controller.device_type
	# Which system this plug fits. The port zone's snap filter reads it off the
	# plug rather than chasing the cable back to the controller.
	if "systemid" in controller:
		systemid = str(controller.get("systemid"))


## Called by system.gd when this plug snaps into a port.
func on_plugged_in(system: RetroSystem, port_index: int) -> void:
	if is_instance_valid(_controller) and _controller.has_method("on_plugged_in"):
		_controller.on_plugged_in(system, port_index)


## Called by system.gd when this plug is removed from a port.
func on_unplugged() -> void:
	if is_instance_valid(_controller) and _controller.has_method("on_unplugged"):
		_controller.on_unplugged()
