## ControllerPlug — the grabbable plug at the end of a retro controller's cable.
## Must be in the "controller_plug" group so RetroSystem controller ports accept it.
class_name ControllerPlug
extends XRToolsPickable


## The controller (RetroController or RayGun) that owns this plug.
var _controller: Node3D = null

## Device type exposed so system.gd can read it without knowing the controller type.
var device_type: int = 1  # RETRO_DEVICE_JOYPAD
## Systemid of the controller on the other end; "" = fits any port.
var systemid: String = ""

## Local point the cable leaves this plug at, fed to VerletRope.end_anchor_offset.
## Zero for the generic cylinder plug, whose origin already sits mid-barrel with
## the strain relief covering it; a bespoke connector sets its own cable boss in
## set_plug_mesh, since its origin is the SEATING reference buried in the shell.
var cable_anchor: Vector3 = Vector3.ZERO


func _ready() -> void:
	super._ready()
	add_to_group("controller_plug")
	picked_up.connect(func(_p: Variant) -> void: PlugAim.aim(self))


## How far this plug may stray, as {anchor: Vector3, length: float}, or {} when
## the cable isn't built yet. Read by function_pickup so a ray grab reels the
## plug along the beam only as far as the cord actually reaches.
##
## Derived from the sibling rope rather than the owning controller, for the same
## reason CablePlug.get_tether is: every owner already sets `start_node` and
## sizes the rope, and there are several of them.
func get_tether() -> Dictionary:
	var rope := get_parent().get_node_or_null("VerletRope")
	if rope == null or not is_instance_valid(rope.start_node):
		return {}
	return {
		"anchor": (rope.start_node as Node3D).global_position,
		"length": float(rope.segment_count) * rope.segment_length,
	}


## Returns the owning controller (RetroController or RayGun).
func get_controller() -> Node3D:
	return _controller


## Swap the generic cylinder plug for a device-accurate connector mesh — the PS/2
## plugs on the keyboard and mouse, generated by Tools/gen_ps2_plug.gd. The mesh is
## authored in this node's own frame (connector on +Z, cable trailing -Z), so it
## needs no transform here.
##
## Re-entrant, and it has to be. Every pad sets this once when its cable spawns,
## because a pad is born knowing its console. A PadReceiver is universal and
## learns its connector only when it seats, so it calls this again on every plug
## and unplug — an empty path putting the generic moulding back, which is also
## what an unlisted console gets rather than keeping the last one's connector.
func set_plug_mesh(path: String) -> void:
	var previous := get_node_or_null("PlugModel")
	# Explicitly typed, not inferred: a ternary over Mesh/null infers Variant, and
	# inferring from Variant is an error in this project.
	var mesh: Mesh = null
	if not path.is_empty() and ResourceLoader.exists(path):
		mesh = load(path) as Mesh
	if previous == null and mesh == null:
		return          # nothing to swap in and nothing to swap out
	if previous != null:
		remove_child(previous)
		previous.queue_free()
	for generic in ["PlugTip", "StrainRelief"]:
		var g := get_node_or_null(generic) as MeshInstance3D
		if g != null:
			g.visible = mesh == null
	if mesh == null:
		cable_anchor = Vector3.ZERO
		return
	var mi := MeshInstance3D.new()
	mi.name = "PlugModel"
	mi.mesh = mesh
	add_child(mi)
	# Where the cable leaves this connector: the centre of the shell's back face
	# (min Z — the cable trails -Z, matching VerletRope.plug_exit_axis).
	var ab: AABB = mesh.get_aabb()
	cable_anchor = Vector3(ab.get_center().x, ab.get_center().y, ab.position.z)


## Called by the owning controller when the cable is spawned.
func set_controller(controller: Node3D) -> void:
	_controller = controller
	if "device_type" in controller:
		device_type = controller.device_type
	# Which system this plug fits. The port zone's snap filter reads it off the
	# plug rather than chasing the cable back to the controller.
	if "systemid" in controller:
		systemid = str(controller.get("systemid"))


## Called by system.gd when this plug snaps into a port.
func on_plugged_in(system: RetroSystem, port_index: int) -> void:
	if is_instance_valid(_controller) and _controller.has_method("on_plugged_in"):
		_controller.on_plugged_in(system, port_index)


## Called by system.gd when this plug is removed from a port.
func on_unplugged() -> void:
	if is_instance_valid(_controller) and _controller.has_method("on_unplugged"):
		_controller.on_unplugged()
